name: Actualizar tasas de cambio

on:
  schedule:
    - cron: '0 * * * *'  # Ejecuta esto cada hora, a la hora en punto
  workflow_dispatch:  # Permite ejecutarlo manualmente.

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Obtener tasas de cambio
        run: |
          # Obtener la respuesta de la API
          curl -s 'https://openexchangerates.org/api/latest.json?app_id=d760b6e976a74d1bbc0fbc45594994f0' > rates.json
          
          # Verificar el contenido de rates.json antes de manipularlo
          cat rates.json

          # Obtener la fecha actual en formato YYYY-MM-DD HH:MM:SS
          updated_time=$(date +'%Y-%m-%d %H:%M:%S')
          
          # Verificar que la variable updated_time tenga el formato correcto
          echo "Fecha de actualización: $updated_time"

          # Usar jq para agregar la fecha de actualización al JSON
          jq --arg updated_time "$updated_time" '. + {actualizado_en: $updated_time}' rates.json > temp.json && mv temp.json rates.json
          
          # Verificar el contenido de rates.json después de agregar la fecha
          cat rates.json
          
      - name: Commit cambios
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Actualizar tasas de cambio'
          add: 'rates.json'
