name: Actualizar tasas de cambio

on:
  schedule:
    - cron: '*/48 * * * *'  # Ejecuta esto cada 48 minutos
  workflow_dispatch:  # Permite ejecutarlo manualmente.

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Obtener tasas de cambio
        run: |
          curl -s 'https://api.exchangeratesapi.io/latest?base=USD&access_key=d760b6e976a74d1bbc0fbc45594994f0' > rates.json

      - name: Agregar hora de la actualización
        run: |
          # Obtener la fecha y hora en formato día/mes/año y hora en formato 12 horas
          current_datetime=$(date +"%d/%m/%Y %I:%M:%S %p") 
          echo "Última actualización: $current_datetime" >> rates.json

      - name: Commit cambios
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Actualizar tasas de cambio'
          add: 'rates.json'
