name: Actualizar tasas de cambio

on:
  schedule:
  - cron: '*/48 * * * *'  # Ejecuta esto cada 48 minutos
  workflow_dispatch:  # Permite ejecutarlo manualmente.

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Obtener tasas de cambio
        run: |
          # Obtener la respuesta de la API
          curl -s 'https://openexchangerates.org/api/latest.json?app_id=d760b6e976a74d1bbc0fbc45594994f0' > rates.json
          
          # Agregar la hora de la actualización en formato Unix
          echo "actualizado_en: $(date +'%Y-%m-%d %H:%M:%S')" >> rates.json
          
      - name: Commit cambios
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Actualizar tasas de cambio'
          add: 'rates.json'
